### List of function in Numpy

##### key NumPy functionalities such as:
  np.array(),  np.arange(),   np.zeros(),  np.ones(),   np.linspace(), np.eye(), 

 

In [7]:
import numpy as np

### Numpy List

In [9]:
# Defining a Python list
my_list = [1, 2, 3] 
type(my_list)

list

In [10]:
# Display the content of the list
my_list

[1, 2, 3]

In [12]:
# Check the type of my_list, which is a Python list
type (my_list)

list

In [13]:
# Convert the list to a numpy array

np.array(my_list)

array([1, 2, 3])

In [14]:
# Display the original list again to show it remains unchanged

my_list

[1, 2, 3]

In [15]:
# Convert the list to a numpy array and store it in my_array

my_array = np.array(my_list)

In [16]:
my_array

array([1, 2, 3])

In [17]:
# check the type of the list

In [18]:
# Check the type of my_array, which is now a numpy ndarray

type (my_array)

numpy.ndarray

### Numpy 2D List: Matrix

In [20]:
# Define a 2D list (matrix)

my_matrix = [[1,2,3], [4,5,6],[7,8,9]]

In [21]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [22]:
type (my_matrix)

list

In [23]:
# Convert the 2D list to a numpy array (2D matrix)

np_matrix = np.array(my_matrix)

In [24]:
np_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Numpy: np.arange (-,-)

In [26]:
# Use np.arange to generate an array with values from 0 to 11 (exclusive)

np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
# Use np.arange to generate an array with a step size of 20

np.arange(0,101,20) #step size

array([  0,  20,  40,  60,  80, 100])

In [28]:
# Check the type of np_matrix, which is a numpy ndarray
type (np_matrix)

numpy.ndarray

### Numpy: np.zeros()

In [30]:
# Generate an array of 5 zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [31]:
# Generate a 2x5 matrix of zeros
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Numpy: np.ones()

In [33]:
# Generate a 2x4 matrix of ones
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
# Generate an array of 5 ones
np.ones(5)

array([1., 1., 1., 1., 1.])

### Numpy: np.linspace()

In [36]:
# Generate 11 equally spaced values between 0 and 10 (inclusive)
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [37]:
# Generate 6 equally spaced values between 0 and 10 (inclusive)
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [38]:
# Get the length of the array generated by linspace
len (np.linspace(0,10,6))

6

### Numpy: np.eye()

In [40]:
# Generate a 4x4 identity matrix (ones on the diagonal, zeros elsewhere)
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Udemy Task:

##### Create a numpy array called myarray which consists of 101 evenly linearly spaced points between 0 and 10.

In [43]:
myarray = np.linspace(0, 10, 101)
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])