### List of function in Numpy

##### Statistical functions like 
.max(), .min(), .argmax(), .argmin()

In [507]:
import numpy as np

### Numpy: .max()

In [562]:
# Find the maximum value in randarr
randarr.max()

98

### Numpy: .min()

In [564]:
# Find the minimum value in randarr
randarr.min()

3

### Numpy: .argmax()

In [566]:
# Find the index of the maximum value in randarr
randarr.argmax()

6

### Numpy: .argmin()

In [568]:
# Find the index of the minimum value in randarr
randarr.argmin()

0

### Numpy: .dtype

In [570]:
# Check the data type of elements in randarr
randarr.dtype

dtype('int32')

In [571]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### Numpy: .shape

In [573]:
# Check the shape of arr
arr.shape

(25,)

### Numpy: .reshape(-,-)

In [575]:
# Reshape arr to 5x5 matrix and display
arr = arr.reshape(5,5)

In [576]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [577]:
arr.shape

(5, 5)

In [578]:
# Reshape arr to a 25x1 matrix
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [579]:
# Reshape arr to a 1x25 matrix
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])