### List of function in Numpy

##### key NumPy functionalities such as:
  np.array(),  np.arange(),   np.zeros(),  np.ones(),   np.linspace(), np.eye(), 

 

##### Random number generation: 
np.random.rand(), np.random.randn(), np.random.randint()).


##### Statistical functions like 
.max(), .min(), .argmax(), .argmin()

In [507]:
import numpy as np

### Numpy List

In [509]:
# Defining a Python list
my_list = [1, 2, 3] 
type(my_list)

list

In [510]:
# Display the content of the list
my_list

[1, 2, 3]

In [512]:
# Check the type of my_list, which is a Python list
type (my_list)

list

In [513]:
# Convert the list to a numpy array

np.array(my_list)

array([1, 2, 3])

In [514]:
# Display the original list again to show it remains unchanged

my_list

[1, 2, 3]

In [515]:
# Convert the list to a numpy array and store it in my_array

my_array = np.array(my_list)

In [516]:
my_array

array([1, 2, 3])

In [517]:
# check the type of the list

In [518]:
# Check the type of my_array, which is now a numpy ndarray

type (my_array)

numpy.ndarray

### Numpy 2D List: Matrix

In [520]:
# Define a 2D list (matrix)

my_matrix = [[1,2,3], [4,5,6],[7,8,9]]

In [521]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [522]:
type (my_matrix)

list

In [523]:
# Convert the 2D list to a numpy array (2D matrix)

np_matrix = np.array(my_matrix)

In [524]:
np_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Numpy: np.arange (-,-)

In [526]:
# Use np.arange to generate an array with values from 0 to 11 (exclusive)

np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [527]:
# Use np.arange to generate an array with a step size of 20

np.arange(0,101,20) #step size

array([  0,  20,  40,  60,  80, 100])

In [528]:
# Check the type of np_matrix, which is a numpy ndarray
type (np_matrix)

numpy.ndarray

### Numpy: np.zeros()

In [530]:
# Generate an array of 5 zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [531]:
# Generate a 2x5 matrix of zeros
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Numpy: np.ones()

In [533]:
# Generate a 2x4 matrix of ones
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [534]:
# Generate an array of 5 ones
np.ones(5)

array([1., 1., 1., 1., 1.])

### Numpy: np.linspace()

In [536]:
# Generate 11 equally spaced values between 0 and 10 (inclusive)
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [537]:
# Generate 6 equally spaced values between 0 and 10 (inclusive)
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [538]:
# Get the length of the array generated by linspace
len (np.linspace(0,10,6))

6

### Numpy: np.eye()

In [540]:
# Generate a 4x4 identity matrix (ones on the diagonal, zeros elsewhere)
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Numpy: np.random.rand()

In [542]:
# Generate 10 random numbers between 0 and 1
np.random.rand(10)

array([0.82026865, 0.44130427, 0.23668364, 0.41805425, 0.93072888,
       0.16710275, 0.75959507, 0.12320217, 0.66885387, 0.70139253])

In [543]:
# Generate a single random number between 0 and 1
np.random.rand(1)

array([0.65790624])

In [544]:
# Generate a 2x4 matrix of random numbers between 0 and 1
np.random.rand(2,4)

array([[0.77098405, 0.93505091, 0.42935846, 0.26513235],
       [0.21279722, 0.21411741, 0.52302267, 0.10497849]])

### Numpy: np.random.randn()

In [546]:
# Generate 10 random numbers from a standard normal distribution (mean=0, std=1)
np.random.randn(10) #Standard Normal Distribution

array([ 1.2320855 ,  1.62145296, -0.15720753,  0.30400945,  1.56620852,
        1.16694228, -0.51487376, -0.21902376,  0.77090534,  0.44450598])

In [547]:
# Generate a 2x3 matrix of random numbers from a standard normal distribution
np.random.randn(2,3) #Standard Normal Distribution

array([[-1.02915618, -0.74194106,  0.96381662],
       [-0.71821582, -0.71397015, -0.12390217]])

### Numpy: np.random.randint()

In [549]:
# Generate a 10x10 matrix of random integers between 0 and 100
np.random.randint(0,101,(10,10))

array([[62, 40, 38, 92, 85, 77, 14, 14, 80, 74],
       [27, 57, 93, 91, 32, 52,  8, 79, 68, 82],
       [79, 13, 32, 87, 96, 37, 81, 60, 62, 22],
       [ 3, 72, 25, 55, 89, 79, 96, 76, 65, 72],
       [42, 83, 83,  4, 79, 12, 16, 92, 54, 50],
       [71,  8, 60,  2, 48, 89,  4, 37, 36, 77],
       [17, 80, 48, 59, 92, 39, 31, 21, 57,  0],
       [60, 53, 85, 91, 27, 55, 29, 88, 15, 21],
       [14, 86, 87, 30, 48,  2, 46, 57, 78, 40],
       [ 3, 50, 89, 83, 94, 96, 23, 25, 11, 95]])

### Numpy: np.random.seed()

In [551]:
# Set the seed for reproducibility and generate 4 random numbers
np.random.seed(104)
np.random.rand(4)

array([0.14792062, 0.22829836, 0.80749336, 0.29847458])

In [552]:
# Generate 4 random numbers without setting the seed (different result each time)
np.random.seed(104)
np.random.rand(4)

array([0.14792062, 0.22829836, 0.80749336, 0.29847458])

In [553]:
#without seed we have diferent result in any time 
np.random.rand(4)

array([0.18570674, 0.77213731, 0.40543952, 0.99590454])

In [554]:
# Generate a 1D array from 0 to 24
arr = np.arange(0,25)

In [555]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### Numpy: .reshape (-,-)

In [557]:
# Reshape the array into a 5x5 matrix
arr.reshape (5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [558]:
# If we try reshaping with incompatible dimensions (5, 4), it will throw an error
# arr.reshape(5, 4)  # This will give an error because the array has 25 elements

#arr.reshape (5,4)

In [559]:
randarr = np.random.randint(0,101,10)

In [560]:
# Generate a random 1D array of 10 random integers between 0 and 100
randarr

array([ 3, 64,  8, 14, 59, 55, 98, 62, 64, 69])

### Numpy: .max()

In [562]:
# Find the maximum value in randarr
randarr.max()

98

### Numpy: .min()

In [564]:
# Find the minimum value in randarr
randarr.min()

3

### Numpy: .argmax()

In [566]:
# Find the index of the maximum value in randarr
randarr.argmax()

6

### Numpy: .argmin()

In [568]:
# Find the index of the minimum value in randarr
randarr.argmin()

0

### Numpy: .dtype

In [570]:
# Check the data type of elements in randarr
randarr.dtype

dtype('int32')

In [571]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### Numpy: .shape

In [573]:
# Check the shape of arr
arr.shape

(25,)

### Numpy: .reshape(-,-)

In [575]:
# Reshape arr to 5x5 matrix and display
arr = arr.reshape(5,5)

In [576]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [577]:
arr.shape

(5, 5)

In [578]:
# Reshape arr to a 25x1 matrix
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [579]:
# Reshape arr to a 1x25 matrix
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

### Udemy Task:

##### Create a numpy array called myarray which consists of 101 evenly linearly spaced points between 0 and 10.

In [582]:
myarray = np.linspace(0, 10, 101)
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])


### This script demonstrates basic NumPy operations such as:
##### "NumPy Array Indexing", "Slicing", and "Conditional Selection":


### 1. Indexing and selecting elements from 1D and 2D arrays.


In [585]:
# Creating a NumPy array from a range of values

arr_arrange = np.arange(0,10)
arr_arrange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [586]:
# Accessing elements using indexing
arr_arrange[8]

8

In [587]:
arr_arrange[0:5]


array([0, 1, 2, 3, 4])

In [588]:
arr_arrange [:5]


array([0, 1, 2, 3, 4])

In [589]:
arr_arrange[5:]


array([5, 6, 7, 8, 9])

In [590]:
arr_arrange[5:10]

array([5, 6, 7, 8, 9])

### 2. Modifying array elements using slicing and broadcasting.


##### broadcasting

In [593]:
arr_arrange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [594]:
# Broadcasting: modifying a section of the array
arr_arrange[5:10] = 100

In [595]:
arr_arrange

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100])

In [596]:
arr = np.arange (0,11)

In [597]:
slice_of_arry = arr [0:5]

##### Slicing

In [599]:
slice_of_arry

array([0, 1, 2, 3, 4])

In [600]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [601]:
# Creating and modifying slices
# the slice of Arry has affected the original array

slice_of_arry [:] = 99 # to select everything

In [602]:
slice_of_arry

array([99, 99, 99, 99, 99])

In [603]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

##### Creating a copy of an array and understanding the effect of slicing on the original array.


In [605]:
# Copying the original array to avoid affecting it
arr_copy = arr.copy()

In [606]:
arr_copy[:] = 100

In [607]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [608]:
# the original array has not been changed because of specifying .copr()
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

##### Indixing on 2d lists or matrix

In [610]:
# 2D Array (Matrix) Example
arr_2d = np.array([[1,2,3],[4,5,6],[67,8,9]])
arr_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [67,  8,  9]])

In [611]:
#number of rows (first), then number of columns (second)
arr_2d.shape

(3, 3)

In [612]:
# Accessing elements in a 2D array
arr_2d[0]

array([1, 2, 3])

In [613]:
arr_2d[2]

array([67,  8,  9])

In [614]:
arr_2d[2][1]

8

In [615]:
arr_2d[2,1]


8

In [616]:
arr_2d [:2,1:]

array([[2, 3],
       [5, 6]])

### 3.conditional selection

In [618]:
# Conditional selection
arr = np.arange (1,11)

In [619]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [620]:
boolean_arr = arr > 4

In [621]:
arr[boolean_arr]

array([ 5,  6,  7,  8,  9, 10])

In [622]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

### Udemy Task:

##### Use numpy to check how many rolls were greater than 2. For example if dice_rolls=[1,2,3] then the answer is 1.


In [625]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

total_rolls_over_two =np.sum(dice_rolls > 2)
total_rolls_over_two


19