### List of function in Numpy

##### Random number generation: 
np.random.rand(), np.random.randn(), np.random.randint()).


In [5]:
import numpy as np

### Numpy: np.random.rand()

In [7]:
# Generate 10 random numbers between 0 and 1
np.random.rand(10)

array([0.00678493, 0.28955576, 0.72614543, 0.94933013, 0.26939505,
       0.08532201, 0.06459564, 0.83136645, 0.41453569, 0.40669998])

In [8]:
# Generate a single random number between 0 and 1
np.random.rand(1)

array([0.69155469])

In [9]:
# Generate a 2x4 matrix of random numbers between 0 and 1
np.random.rand(2,4)

array([[8.75854429e-01, 9.43945567e-02, 2.82226174e-01, 1.39718466e-01],
       [4.53985275e-01, 8.02487565e-01, 4.39291563e-01, 8.06899841e-05]])

### Numpy: np.random.randn()

In [11]:
# Generate 10 random numbers from a standard normal distribution (mean=0, std=1)
np.random.randn(10) #Standard Normal Distribution

array([-1.92423769, -0.06328219, -0.2212123 , -0.01708245,  0.80930837,
       -0.41854208, -0.73576529,  0.6556535 , -0.57061574, -1.47840272])

In [12]:
# Generate a 2x3 matrix of random numbers from a standard normal distribution
np.random.randn(2,3) #Standard Normal Distribution

array([[ 0.08790043, -0.64356071,  2.37741323],
       [-0.44136515,  2.25070807,  0.69590795]])

### Numpy: np.random.randint()

In [14]:
# Generate a 10x10 matrix of random integers between 0 and 100
np.random.randint(0,101,(10,10))

array([[ 33,  25,  84,  10,  97,  85,  46,  43,  73,  18],
       [ 45,  30,   7,  50,  81,  23,  87,  19,  31,  38],
       [ 33,  63,  91,   8,  94,  13,  48,  34,   1,  91],
       [ 88,  36,  85,  63,  59,  33,  67,   3,  68,  54],
       [ 22,  22,  80,  43,  94,  51,  26,  42,  77,  71],
       [ 42,  69,  13,  28,  38,  97,  80,  82,  50,  45],
       [ 97,  32,  41,  10,  92,  29,  53,  43,  90,  35],
       [  9,  33,  88,  10,  28,  66,  83,  46,  18,  58],
       [ 90,  23,  87,  80,  52,  76,  60,  22,  83,  23],
       [ 15,  67,  37,  34,  85, 100,  29,  54,  28,  94]])

### Numpy: np.random.seed()

In [16]:
# Set the seed for reproducibility and generate 4 random numbers
np.random.seed(104)
np.random.rand(4)

array([0.14792062, 0.22829836, 0.80749336, 0.29847458])

In [17]:
# Generate 4 random numbers without setting the seed (different result each time)
np.random.seed(104)
np.random.rand(4)

array([0.14792062, 0.22829836, 0.80749336, 0.29847458])

In [18]:
#without seed we have diferent result in any time 
np.random.rand(4)

array([0.18570674, 0.77213731, 0.40543952, 0.99590454])

In [19]:
# Generate a 1D array from 0 to 24
arr = np.arange(0,25)

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### Numpy: .reshape (-,-)

In [22]:
# Reshape the array into a 5x5 matrix
arr.reshape (5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
# If we try reshaping with incompatible dimensions (5, 4), it will throw an error
# arr.reshape(5, 4)  # This will give an error because the array has 25 elements

#arr.reshape (5,4)

In [24]:
randarr = np.random.randint(0,101,10)

In [25]:
# Generate a random 1D array of 10 random integers between 0 and 100
randarr

array([ 3, 64,  8, 14, 59, 55, 98, 62, 64, 69])