
### This script demonstrates basic NumPy operations such as:
##### "NumPy Array Indexing", "Slicing", and "Conditional Selection":


### 1. Indexing and selecting elements from 1D and 2D arrays.


In [585]:
# Creating a NumPy array from a range of values

arr_arrange = np.arange(0,10)
arr_arrange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [586]:
# Accessing elements using indexing
arr_arrange[8]

8

In [587]:
arr_arrange[0:5]


array([0, 1, 2, 3, 4])

In [588]:
arr_arrange [:5]


array([0, 1, 2, 3, 4])

In [589]:
arr_arrange[5:]


array([5, 6, 7, 8, 9])

In [590]:
arr_arrange[5:10]

array([5, 6, 7, 8, 9])

### 2. Modifying array elements using slicing and broadcasting.


##### broadcasting

In [593]:
arr_arrange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [594]:
# Broadcasting: modifying a section of the array
arr_arrange[5:10] = 100

In [595]:
arr_arrange

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100])

In [596]:
arr = np.arange (0,11)

In [597]:
slice_of_arry = arr [0:5]

##### Slicing

In [599]:
slice_of_arry

array([0, 1, 2, 3, 4])

In [600]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [601]:
# Creating and modifying slices
# the slice of Arry has affected the original array

slice_of_arry [:] = 99 # to select everything

In [602]:
slice_of_arry

array([99, 99, 99, 99, 99])

In [603]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

##### Creating a copy of an array and understanding the effect of slicing on the original array.


In [605]:
# Copying the original array to avoid affecting it
arr_copy = arr.copy()

In [606]:
arr_copy[:] = 100

In [607]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [608]:
# the original array has not been changed because of specifying .copr()
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

##### Indixing on 2d lists or matrix

In [610]:
# 2D Array (Matrix) Example
arr_2d = np.array([[1,2,3],[4,5,6],[67,8,9]])
arr_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [67,  8,  9]])

In [611]:
#number of rows (first), then number of columns (second)
arr_2d.shape

(3, 3)

In [612]:
# Accessing elements in a 2D array
arr_2d[0]

array([1, 2, 3])

In [613]:
arr_2d[2]

array([67,  8,  9])

In [614]:
arr_2d[2][1]

8

In [615]:
arr_2d[2,1]


8

In [616]:
arr_2d [:2,1:]

array([[2, 3],
       [5, 6]])

### 3.conditional selection

In [618]:
# Conditional selection
arr = np.arange (1,11)

In [619]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [620]:
boolean_arr = arr > 4

In [621]:
arr[boolean_arr]

array([ 5,  6,  7,  8,  9, 10])

In [622]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

### Udemy Task:

##### Use numpy to check how many rolls were greater than 2. For example if dice_rolls=[1,2,3] then the answer is 1.


In [625]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

total_rolls_over_two =np.sum(dice_rolls > 2)
total_rolls_over_two


19